version: '2'
services:
  web:
    image: fe/koa_app:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    volumes:
      - ./config:/var/www/config
      - ./app/public:/var/www/app/public
      - ~/.ssh:/root/.ssh
    ports:
      - "7002:7002"
    links:
      - "redis"
      - "mysql"

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: koa_app
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pwd
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redis-volume:/data

volumes:
  mysql-volume:
  redis-volume:
  koa-app-config:
  koa-app-public:
